-- Penguatan penilaian juri. Jalankan setelah migrasi multi-juri, auth juri, dan auth admin.

CREATE TABLE IF NOT EXISTS public.kriteria_penilaian (
  cabang_lomba TEXT NOT NULL,
  kode TEXT NOT NULL,
  label TEXT NOT NULL,
  bobot NUMERIC(5,2) NOT NULL CHECK (bobot > 0 AND bobot <= 100),
  nilai_maksimum INTEGER NOT NULL DEFAULT 100 CHECK (nilai_maksimum > 0),
  urutan INTEGER NOT NULL,
  aktif BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (cabang_lomba, kode)
);

ALTER TABLE public.kriteria_penilaian ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Pengguna login membaca kriteria penilaian" ON public.kriteria_penilaian;
CREATE POLICY "Pengguna login membaca kriteria penilaian"
ON public.kriteria_penilaian FOR SELECT TO authenticated
USING (true);

INSERT INTO public.kriteria_penilaian (cabang_lomba, kode, label, bobot, nilai_maksimum, urutan) VALUES
  ('Adzan','makhraj','Ketepatan bacaan & makhraj',35,100,1),
  ('Adzan','lafaz','Kelancaran & ketepatan lafaz',25,100,2),
  ('Adzan','irama','Suara & irama',20,100,3),
  ('Adzan','adab','Adab & sikap',10,100,4),
  ('Adzan','keberanian','Keberanian & percaya diri',10,100,5),
  ('MHQ','kelancaran','Kelancaran hafalan',35,100,1),
  ('MHQ','ketepatan','Ketepatan bacaan',30,100,2),
  ('MHQ','tajwid','Makhraj & tajwid',25,100,3),
  ('MHQ','adab','Adab & sikap',10,100,4),
  ('Menyanyi Solo','nada','Ketepatan nada & melodi',30,100,1),
  ('Menyanyi Solo','vokal','Vokal & kejelasan suara',25,100,2),
  ('Menyanyi Solo','ekspresi','Penghayatan & ekspresi',20,100,3),
  ('Menyanyi Solo','penampilan','Percaya diri & penampilan',15,100,4),
  ('Menyanyi Solo','kesesuaian_lagu','Kesesuaian lagu',10,100,5),
  ('Fashion Show','tema','Kesesuaian dengan tema',25,100,1),
  ('Fashion Show','kreativitas','Kreativitas busana',25,100,2),
  ('Fashion Show','ekspresi','Penampilan & ekspresi',20,100,3),
  ('Fashion Show','percaya_diri','Kepercayaan diri',20,100,4),
  ('Fashion Show','kerapian','Kerapian',10,100,5),
  ('Karya Kolase','tema','Kesesuaian tema',25,100,1),
  ('Karya Kolase','kreativitas','Kreativitas',25,100,2),
  ('Karya Kolase','komposisi','Komposisi & pemilihan bahan',20,100,3),
  ('Karya Kolase','kerapian','Kerapian & ketepatan menempel',20,100,4),
  ('Karya Kolase','kebersihan','Kebersihan & hasil akhir',10,100,5),
  ('Mewarnai','kesesuaian','Kesesuaian & ketepatan mewarnai',30,100,1),
  ('Mewarnai','kerapian','Kerapian',25,100,2),
  ('Mewarnai','komposisi','Komposisi & pemilihan warna',25,100,3),
  ('Mewarnai','kreativitas','Kreativitas',10,100,4),
  ('Mewarnai','kebersihan','Kebersihan hasil karya',10,100,5),
  ('Tendangan Penalti','skor_utama','Skor utama',100,3,1)
ON CONFLICT (cabang_lomba, kode) DO UPDATE SET
  label = EXCLUDED.label, bobot = EXCLUDED.bobot,
  nilai_maksimum = EXCLUDED.nilai_maksimum, urutan = EXCLUDED.urutan, aktif = true;

ALTER TABLE public.penilaian_juri DROP CONSTRAINT IF EXISTS penilaian_juri_status_check;
ALTER TABLE public.penilaian_juri
  ADD CONSTRAINT penilaian_juri_status_check CHECK (status IN ('draft','final','locked'));
ALTER TABLE public.penilaian_juri ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;
ALTER TABLE public.penilaian_juri ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
ALTER TABLE public.penilaian_juri ADD COLUMN IF NOT EXISTS locked_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.audit_penilaian_juri (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penilaian_juri_id UUID,
  pendaftar_id UUID,
  juri_id UUID,
  aksi TEXT NOT NULL CHECK (aksi IN ('INSERT','UPDATE','DELETE')),
  status_lama TEXT,
  status_baru TEXT,
  data_lama JSONB,
  data_baru JSONB,
  actor_user_id UUID,
  actor_role TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_penilaian_pendaftar_idx ON public.audit_penilaian_juri (pendaftar_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_penilaian_juri_idx ON public.audit_penilaian_juri (juri_id, created_at DESC);

ALTER TABLE public.audit_penilaian_juri ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin membaca audit penilaian" ON public.audit_penilaian_juri;
CREATE POLICY "Admin membaca audit penilaian" ON public.audit_penilaian_juri
FOR SELECT TO authenticated
USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

CREATE OR REPLACE FUNCTION public.validasi_penilaian_juri()
RETURNS TRIGGER AS $$
DECLARE
  kategori TEXT;
  jumlah_kriteria INTEGER;
  jumlah_detail_valid INTEGER;
  hasil NUMERIC := 0;
  criterion RECORD;
  nilai NUMERIC;
  is_admin BOOLEAN := COALESCE((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false);
BEGIN
  SELECT cabang_lomba INTO kategori FROM public.pendaftar WHERE id = NEW.pendaftar_id;
  IF kategori IS NULL THEN RAISE EXCEPTION 'Peserta tidak ditemukan'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.juri j
    JOIN public.juri_kategori jk ON jk.juri_id = j.id
    WHERE j.id = NEW.juri_id AND j.aktif = true AND jk.cabang_lomba = kategori
  ) THEN
    RAISE EXCEPTION 'Juri tidak aktif atau tidak ditugaskan pada kategori peserta';
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status = 'locked' THEN
    RAISE EXCEPTION 'Nilai sudah dikunci dan tidak dapat diubah';
  END IF;
  IF NEW.status = 'locked' AND NOT is_admin THEN
    RAISE EXCEPTION 'Hanya admin yang dapat mengunci nilai';
  END IF;

  SELECT COUNT(*) INTO jumlah_kriteria FROM public.kriteria_penilaian
  WHERE cabang_lomba = kategori AND aktif = true;
  SELECT COUNT(*) INTO jumlah_detail_valid
  FROM jsonb_object_keys(COALESCE(NEW.detail_nilai, '{}'::jsonb)) AS d(kode)
  WHERE EXISTS (
    SELECT 1 FROM public.kriteria_penilaian kp
    WHERE kp.cabang_lomba = kategori AND kp.kode = d.kode AND kp.aktif = true
  );

  IF NEW.status IN ('final','locked') AND jumlah_detail_valid <> jumlah_kriteria THEN
    RAISE EXCEPTION 'Semua kriteria wajib diisi sebelum nilai difinalkan';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_object_keys(COALESCE(NEW.detail_nilai, '{}'::jsonb)) d(kode)
    WHERE NOT EXISTS (SELECT 1 FROM public.kriteria_penilaian kp WHERE kp.cabang_lomba = kategori AND kp.kode = d.kode AND kp.aktif)
  ) THEN
    RAISE EXCEPTION 'Detail nilai mengandung kriteria yang tidak valid';
  END IF;

  FOR criterion IN SELECT * FROM public.kriteria_penilaian WHERE cabang_lomba = kategori AND aktif ORDER BY urutan LOOP
    IF NEW.detail_nilai ? criterion.kode THEN
      BEGIN
        nilai := (NEW.detail_nilai ->> criterion.kode)::NUMERIC;
      EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'Nilai kriteria % harus berupa angka', criterion.kode;
      END;
      IF nilai < 0 OR nilai > criterion.nilai_maksimum THEN
        RAISE EXCEPTION 'Nilai kriteria % harus antara 0 dan %', criterion.kode, criterion.nilai_maksimum;
      END IF;
      hasil := hasil + (nilai / criterion.nilai_maksimum * 100) * (criterion.bobot / 100);
    END IF;
  END LOOP;

  NEW.nilai_total := ROUND(hasil);
  NEW.updated_at := now();
  IF NEW.status IN ('final','locked') AND (TG_OP = 'INSERT' OR OLD.status = 'draft') THEN NEW.finalized_at := now(); END IF;
  IF NEW.status = 'locked' THEN NEW.locked_at := now(); NEW.locked_by := auth.uid(); END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS validasi_penilaian_juri_trigger ON public.penilaian_juri;
CREATE TRIGGER validasi_penilaian_juri_trigger
BEFORE INSERT OR UPDATE ON public.penilaian_juri
FOR EACH ROW EXECUTE FUNCTION public.validasi_penilaian_juri();

CREATE OR REPLACE FUNCTION public.audit_perubahan_penilaian()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.audit_penilaian_juri (
    penilaian_juri_id, pendaftar_id, juri_id, aksi, status_lama, status_baru,
    data_lama, data_baru, actor_user_id, actor_role
  ) VALUES (
    COALESCE(NEW.id, OLD.id), COALESCE(NEW.pendaftar_id, OLD.pendaftar_id), COALESCE(NEW.juri_id, OLD.juri_id), TG_OP,
    CASE WHEN TG_OP <> 'INSERT' THEN OLD.status END, CASE WHEN TG_OP <> 'DELETE' THEN NEW.status END,
    CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END, CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END,
    auth.uid(), COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', 'juri')
  );
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS audit_penilaian_juri_trigger ON public.penilaian_juri;
CREATE TRIGGER audit_penilaian_juri_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.penilaian_juri
FOR EACH ROW EXECUTE FUNCTION public.audit_perubahan_penilaian();

CREATE OR REPLACE FUNCTION public.sync_nilai_akhir_peserta()
RETURNS TRIGGER AS $$
DECLARE
  target_pendaftar UUID := CASE WHEN TG_OP = 'DELETE' THEN OLD.pendaftar_id ELSE NEW.pendaftar_id END;
  total_juri INTEGER;
  total_selesai INTEGER;
  jumlah_nilai INTEGER;
BEGIN
  SELECT COUNT(DISTINCT j.id) INTO total_juri
  FROM public.pendaftar p
  JOIN public.juri_kategori jk ON jk.cabang_lomba = p.cabang_lomba
  JOIN public.juri j ON j.id = jk.juri_id AND j.aktif = true
  WHERE p.id = target_pendaftar;

  SELECT COUNT(DISTINCT pj.juri_id), SUM(pj.nilai_total)::INTEGER
  INTO total_selesai, jumlah_nilai
  FROM public.penilaian_juri pj
  JOIN public.juri j ON j.id = pj.juri_id AND j.aktif = true
  JOIN public.pendaftar p ON p.id = pj.pendaftar_id
  JOIN public.juri_kategori jk ON jk.juri_id = pj.juri_id AND jk.cabang_lomba = p.cabang_lomba
  WHERE pj.pendaftar_id = target_pendaftar AND pj.status IN ('final','locked');

  UPDATE public.pendaftar
  SET nilai_total = CASE WHEN total_juri > 0 AND total_selesai = total_juri THEN jumlah_nilai ELSE NULL END
  WHERE id = target_pendaftar;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Hitung ulang semua nilai lama setelah aturan baru terpasang.
UPDATE public.pendaftar p SET nilai_total = (
  SELECT CASE WHEN COUNT(DISTINCT pj.juri_id) = (
    SELECT COUNT(DISTINCT j.id) FROM public.juri_kategori jk JOIN public.juri j ON j.id = jk.juri_id AND j.aktif
    WHERE jk.cabang_lomba = p.cabang_lomba
  ) THEN SUM(pj.nilai_total)::INTEGER ELSE NULL END
  FROM public.penilaian_juri pj JOIN public.juri j ON j.id = pj.juri_id AND j.aktif
  WHERE pj.pendaftar_id = p.id AND pj.status IN ('final','locked')
);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.penilaian_juri;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;
